<?php

return [
    /*
     * Vehicles
     */
    'vehicles' => [
        'pop_ford_gt402'                       => ['name' => 'Ford GT40 Azul', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_ford_gt403'                       => ['name' => 'Ford GT40 Rojo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_amg_GT_rojo'                      => ['name' => 'Mercedes AMG GT rojo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_laferrari_D'                      => ['name' => 'Ferrari LaFerrari', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_laferrari_amarillo'               => ['name' => 'Ferrari LaFerrari Amarillo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_furai'                            => ['name' => 'Mazda Furai', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mp1_D'                            => ['name' => 'McLaren P1', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_naranja'                => ['name' => 'Chevrolet Corvette Super Sport Naranja', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_negro'                  => ['name' => 'Chevrolet Corvette Super Sport Negro', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_azul'                   => ['name' => 'Chevrolet Corvette Super Sport Amarillo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_amarillo'               => ['name' => 'Chevrolet Corvette Super Sport Amarillo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_zonda_s1'                         => ['name' => 'Zonda S', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_r8MP_4'                           => ['name' => 'Audi  R8 LMP900 5', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_r8MP_5'                           => ['name' => 'Audi R8 LMP900 6', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_r8MP_3'                           => ['name' => 'Audi R8 LMP900 4', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mono'                             => ['name' => 'BAC Mono', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Caterham_2'                       => ['name' => 'Caterham R500 Amarillo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Caterham_3'                       => ['name' => 'Caterham R500 Blanco y Rojo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_GT3'                              => ['name' => 'Nissan GT-R Nismo GT3', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_GT3_blanco'                       => ['name' => 'Nissan GT-R Nismo GT3 Sport Blanco', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_GT3_azul'                         => ['name' => 'Nissan GT-R Nismo GT3 Sport Azul', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_2'                     => ['name' => 'Megane GT3 2', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lola_1'                           => ['name' => 'Aston Martin DBR1-2 1', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lola_2'                           => ['name' => 'Aston Martin DBR1-2 2', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lola_4'                           => ['name' => 'Aston Martin DBR-1-2 4', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lola_7'                           => ['name' => 'Aston Martin DBR1-2 7', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lola_8'                           => ['name' => 'Aston Martin DBR1-2 8', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lola_9'                           => ['name' => 'Aston Martin DBR1-2 9', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'C_Kart_01_Blu_F'                      => ['name' => 'Kart (Bluking)', 'price' => 2250, 'side' => 'civ', 'type' => 'Car'],
        'C_Kart_01_Fuel_F'                     => ['name' => 'Kart (Fuel)', 'price' => 2250, 'side' => 'civ', 'type' => 'Car'],
        'C_Kart_01_Red_F'                      => ['name' => 'Kart (Redstone)', 'price' => 2250, 'side' => 'civ', 'type' => 'Car'],
        'C_Kart_01_Vrana_F'                    => ['name' => 'Kart (Vrana)', 'price' => 2250, 'side' => 'civ', 'type' => 'Car'],
        'pop_bus_p_noir'                       => ['name' => 'Autobus Man Negro', 'price' => 9750, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_taxi_civ'              => ['name' => 'Peugeot 508 Taxi', 'price' => 5250, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_qashqai_2016_poptv1'       => ['name' => 'Nissan QashQai 2016 POPTV Rojo', 'price' => 24000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_qashqai_2016_poptv2'       => ['name' => 'Nissan QashQai 2016 POPTV Negro', 'price' => 24000, 'side' => 'civ', 'type' => 'Car'],
        'pop_sprinter_poptv1'                  => ['name' => 'Mercedes Sprinter 2016 POTV Negra', 'price' => 24000, 'side' => 'civ', 'type' => 'Car'],
        'pop_sprinter_poptv2'                  => ['name' => 'Mercedes Sprinter 2016 POPTV Roja', 'price' => 24000, 'side' => 'civ', 'type' => 'Car'],
        'mr_stretcher'                         => ['name' => 'EMS Stretcher', 'price' => 375, 'side' => 'med', 'type' => 'Car'],
        'pop_fiat_bravo_ems1'                  => ['name' => 'Fiat Bravo EMS', 'price' => 3750, 'side' => 'med', 'type' => 'Car'],
        'pop_grua'                             => ['name' => 'Grua Mapfre', 'price' => 375, 'side' => 'med', 'type' => 'Car'],
        'pop_mitsubishi_asx_ems1'              => ['name' => 'Mitsubishi ASX EMS', 'price' => 3750, 'side' => 'med', 'type' => 'Car'],
        'pop_ford_transit_amb1'                => ['name' => 'Ford Transit EMS', 'price' => 1500, 'side' => 'med', 'type' => 'Car'],
        'POP_corbillard_c'                     => ['name' => 'Corbillard', 'price' => 1500, 'side' => 'med', 'type' => 'Car'],
        'pop_renault_master_amb1'              => ['name' => 'Renault Master EMS', 'price' => 2250, 'side' => 'med', 'type' => 'Car'],
        'pop_sprinter_amb1'                    => ['name' => 'Mercedes Sprinter EMS', 'price' => 3000, 'side' => 'med', 'type' => 'Car'],
        'pop_sprinter_caja_amb1'               => ['name' => 'Mercedes Sprinter UVI MOVIL EMS', 'price' => 4500, 'side' => 'med', 'type' => 'Car'],
        'pop_sprinter_2016_amb1'               => ['name' => 'Mercedes Sprinter 2016 EMS', 'price' => 3750, 'side' => 'med', 'type' => 'Car'],
        'pop_sprinter_corta_amb1'              => ['name' => 'Mercedes Sprinter Corta EMS', 'price' => 3750, 'side' => 'med', 'type' => 'Car'],
        'ec135_ems_F'                          => ['name' => 'Airbus HC EC135 - EMS', 'price' => 7500, 'side' => 'med', 'type' => 'Air'],
        'gazelle_civil_4'                      => ['name' => 'Gazelle SA 342 (EMS)', 'price' => 6750, 'side' => 'med', 'type' => 'Air'],
        'PKE_92_civ_bleufonce'                 => ['name' => 'Porsche 911 92  Bleu fonce', 'price' => 825000, 'side' => 'civ', 'type' => 'Car'],
        'PKE_92_civ_jaune'                     => ['name' => 'Porsche 911 92  Amarillo', 'price' => 825000, 'side' => 'civ', 'type' => 'Car'],
        'PKE_92_civ_rose'                      => ['name' => 'Porsche 911 92  Rosa', 'price' => 825000, 'side' => 'civ', 'type' => 'Car'],
        'PKE_92_civ_grise'                     => ['name' => 'Porsche 911 92  Grise', 'price' => 825000, 'side' => 'civ', 'type' => 'Car'],
        'PKE_92_civ_violet'                    => ['name' => 'Porsche 911 92  Violeta', 'price' => 825000, 'side' => 'civ', 'type' => 'Car'],
        'PKE_92_civ_orange'                    => ['name' => 'Porsche 911 92  Naranja', 'price' => 825000, 'side' => 'civ', 'type' => 'Car'],
        'pop_cayenne_p_negro'                  => ['name' => 'Porsche Cayenne Noir', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_cayenne_p_azul'                   => ['name' => 'Porsche Cayenne Bleu fonce', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_cayenne_p_rojo'                   => ['name' => 'Porsche Cayenne Rouge', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_cayenne_p_amarillo'               => ['name' => 'Porsche Cayenne Jaune', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_cayenne_p_rosa'                   => ['name' => 'Porsche Cayenne Rose', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_cayenne_p_gris'                   => ['name' => 'Porsche Cayenne Grise', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_cayenne_p_violeta'                => ['name' => 'Porsche Cayenne Violette', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_cayenne_p_naranja'                => ['name' => 'Porsche Cayenne Orange', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm4_D'                          => ['name' => 'BMW M4 SUPER SPORT 2', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm4_D1'                         => ['name' => 'BMW M4 SUPER SPORT 3', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm4_D2'                         => ['name' => 'BMW M4 SUPER SPORT 4', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_camaro_azul'            => ['name' => 'Chevrolet Camaro ZL1 (Azul)', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_camaro_amarillo'        => ['name' => 'Chevrolet Camaro ZL1 (Amarillo)', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_silvia2'                   => ['name' => 'Nissan silvia Azul', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_silvia3'                   => ['name' => 'Nissan silvia Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_300c_r'                           => ['name' => 'POP Chrysler 300C 2007', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_MustangMach1Jet1969'              => ['name' => 'POP Mustang Mach1 Jet1969 Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_BMW750il_r'                       => ['name' => 'POP BMW 750 il Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Chrysler_r'                       => ['name' => 'POP Chrysler 300C Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_skyline2'                  => ['name' => 'Nissan Skyline Azul', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_skyline3'                  => ['name' => 'Nissan Skyline Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_caymanS_z_noir'                   => ['name' => 'Porsche Cayman Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lotus_GTE'                        => ['name' => 'Lotus Evora GTE', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lotus_GTE_azul'                   => ['name' => 'Lotus Evora GTE Azul', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lotus_GTE_negro'                  => ['name' => 'Lotus Evora GTE Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lotus_GTE_amarillo'               => ['name' => 'Lotus Evora GTE Amarillo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_afla_4C_azul'                     => ['name' => 'Alfa Romeo 4C Azul', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_370Z_rojo'                        => ['name' => 'Nissan 370Z Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_MaybachLaundet57'                 => ['name' => 'POP Mercedes S 500', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevroletc7_naranja'              => ['name' => 'Chevrolet Corvette Stingray C7 naranja', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevroletc7_amarillo'             => ['name' => 'Chevrolet Corvette Stingray C7 amarillo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevroletc7_azul'                 => ['name' => 'Chevrolet Corvette Stingray C7 azul', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_regera_naranja'                   => ['name' => 'Koenigsegg Regera naranja', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_regera_amarillo'                  => ['name' => 'Koenigsegg Regera amarillo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_regera_azul'                      => ['name' => 'Koenigsegg Regera azul', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw507_d3'                        => ['name' => 'Bmw 507 blanco custom', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw507_d1'                        => ['name' => 'Bmw 507 rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw507_d2'                        => ['name' => 'Bmw 507 blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lambo_miura_d'                    => ['name' => 'Lamborghini Miura', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw8_rojo'                        => ['name' => 'BMW I8 Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_m300sl1'                          => ['name' => 'Mercedes-Benz 300 SL Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_m300sl2'                          => ['name' => 'Mercedes-Benz 300 SL Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Viper_08_n'                       => ['name' => 'POP Dodge Viper 2008 Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Viper_08_b'                       => ['name' => 'POP Dodge Viper 2008 Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_RollsRoycePHLimo'                 => ['name' => 'POP Rolls Royce Phantom Limo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_RollsRoycePH_b'                   => ['name' => 'POP Rolls Royce Phantom Blanco 2000', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_RollsRoyce011_b'                  => ['name' => 'POP RollsRoyce Phantom Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_NissanGTR_n'                      => ['name' => 'POP Nissan GTR 2015 Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Charger_12_r'                     => ['name' => 'POP Dodge Charger 2012 Rojo', 'price' => 825000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1series'                      => ['name' => 'BMW 1 Series M 2011', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1series_bleufonce'            => ['name' => 'BMW 1 Series M 2011  Bleu fonce', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1series_grise'                => ['name' => 'BMW 1 Series M 2011  Grise', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1series_jaune'                => ['name' => 'BMW 1 Series M 2011  Jaune', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1series_noir'                 => ['name' => 'BMW 1 Series M 2011  Noir', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1series_orange'               => ['name' => 'BMW 1 Series M 2011  Orange', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1series_rose'                 => ['name' => 'BMW 1 Series M 2011  Rose', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1series_rouge'                => ['name' => 'BMW 1 Series M 2011  Rouge', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1series_violet'               => ['name' => 'BMW 1 Series M 2011  Violette', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_limo_civ_bleufonce'           => ['name' => 'Limousine Audi  Azul', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_limo_civ_rose'                => ['name' => 'Limousine Audi  Rosa', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_porche918'                        => ['name' => 'Porsche 918 Spyder', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'POP_veneno_azul'                      => ['name' => 'Lamborghini Veneno Azul', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'POP_veneno_Amarillo'                  => ['name' => 'Lamborghini Veneno Amarillo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bus_p_bleufonce'                  => ['name' => 'Autobus Man Azul Fuerte', 'price' => 9750, 'side' => 'civ', 'type' => 'Car'],
        'pop_bus_p_rouge'                      => ['name' => 'Autobus Man Rojo', 'price' => 9750, 'side' => 'civ', 'type' => 'Car'],
        'pop_bus_p_jaune'                      => ['name' => 'Autobus Man Amarillo', 'price' => 9750, 'side' => 'civ', 'type' => 'Car'],
        'pop_bus_p_rose'                       => ['name' => 'Autobus Man Rosa', 'price' => 9750, 'side' => 'civ', 'type' => 'Car'],
        'pop_bus_p_grise'                      => ['name' => 'Autobus Man Gris', 'price' => 9750, 'side' => 'civ', 'type' => 'Car'],
        'pop_bus_p_violet'                     => ['name' => 'Autobus Man Violeta', 'price' => 9750, 'side' => 'civ', 'type' => 'Car'],
        'pop_bus_p_orange'                     => ['name' => 'Autobus Man Naranja', 'price' => 97500, 'side' => 'civ', 'type' => 'Car'],
        'pop_quad_1'                           => ['name' => 'Yamaha YFZ 750', 'price' => 2250, 'side' => 'civ', 'type' => 'Car'],
        'shounka_harley_a3'                    => ['name' => 'Harley', 'price' => 4500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_harley_a3_noir'               => ['name' => 'Harley Negra', 'price' => 4500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_harley_a3_bleu'               => ['name' => 'Harley Azul', 'price' => 4500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_harley_a3_rouge'              => ['name' => 'Harley Rojo', 'price' => 4500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_harley_a3_lolz'               => ['name' => 'Harley Lolz', 'price' => 4500, 'side' => 'civ', 'type' => 'Car'],
        'pop_quad_sport'                       => ['name' => 'Yamaha YFZ 750 Sport', 'price' => 5250, 'side' => 'civ', 'type' => 'Car'],
        'pop_yamaha_p'                         => ['name' => 'Yahama R6', 'price' => 3300, 'side' => 'civ', 'type' => 'Car'],
        'pop_yamaha_p_bf'                      => ['name' => 'Yahama R6  Bleu fonce', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_yamaha_p_g'                       => ['name' => 'Yahama R6  Grise', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_yamaha_p_j'                       => ['name' => 'Yahama R6  Jaune', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_yamaha_p_noir'                    => ['name' => 'Yahama R6  Noir', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_yamaha_p_o'                       => ['name' => 'Yahama R6  Orange', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_yamaha_p_rose'                    => ['name' => 'Yahama R6  Rose', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_yamaha_p_r'                       => ['name' => 'Yahama R6  Rouge', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_moto_sidecar'                     => ['name' => 'Bmw R75', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_moto_1_azul'                      => ['name' => 'Bagger Azul', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_moto_1_roja'                      => ['name' => 'Bagger Roja', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_moto_1_amarilla'                  => ['name' => 'Bagger Amarilla', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_moto_2_negra'                     => ['name' => 'Hexer Negra', 'price' => 4890, 'side' => 'civ', 'type' => 'Car'],
        'pop_honda_bizz_Roja'                  => ['name' => 'Honda Bizz Roja', 'price' => 3000, 'side' => 'civ', 'type' => 'Car'],
        'pop_honda_bizz_Amarilla'              => ['name' => 'Honda Bizz Amarilla', 'price' => 3000, 'side' => 'civ', 'type' => 'Car'],
        'pop_honda_bizz_Azul'                  => ['name' => 'Honda Bizz Azul', 'price' => 3000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_buggy_noir'                   => ['name' => 'Buggy Negro', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_buggy_bleufonce'              => ['name' => 'Buggy Azul', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_buggy_rouge'                  => ['name' => 'Buggy Rojo', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_buggy_jaune'                  => ['name' => 'Buggy Amarillo', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_buggy_rose'                   => ['name' => 'Buggy Rosa', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_buggy_grise'                  => ['name' => 'Buggy Gris', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_buggy_violet'                 => ['name' => 'Buggy Violeta', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_buggy_orange'                 => ['name' => 'Buggy Naranja', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_JeepWrangler_r'                   => ['name' => 'POP Jeep Wrangler Rojo', 'price' => 127500, 'side' => 'civ', 'type' => 'Car'],
        'pop_volvo2'                           => ['name' => 'Volvo Xc90 Azul', 'price' => 195000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dacia_negro'                      => ['name' => 'Dacia Buster Negro', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dacia_rojo'                       => ['name' => 'Dacia Buster Rojo', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dacia_naranja'                    => ['name' => 'Dacia Buster Naranja', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_ranger_rover3'                    => ['name' => 'Range Rover  Rojo', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_hyundai_x352'                     => ['name' => 'Hyundai X35 Azul', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_rover_evo_amarillo'               => ['name' => 'Range Rover Evoque Amarillo', 'price' => 232500, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_qashqai2'                  => ['name' => 'Nissan Qashqai Azul', 'price' => 247500, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_qashqai3'                  => ['name' => 'Nissan Qashqai Rojo', 'price' => 247500, 'side' => 'civ', 'type' => 'Car'],
        'pop_GMCSerriaLarge_r'                 => ['name' => 'GMC rojo', 'price' => 277500, 'side' => 'civ', 'type' => 'Car'],
        'pop_toyota_FJCruiser2'                => ['name' => 'Toyota FJCruiser Azul', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_toyota_FJCruiser3'                => ['name' => 'Toyota FJCruiser Rojo', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_lexus_gx4602'                     => ['name' => 'Lexus Gx460 Azul', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_jeep_grandcherokee2'              => ['name' => 'Jeep Grand Cherokee Azul', 'price' => 285000, 'side' => 'civ', 'type' => 'Car'],
        'pop_jeep_grandcherokee3'              => ['name' => 'Jeep Grand Cherokee Rojo', 'price' => 285000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_pathfinder2'               => ['name' => 'Nissan Pathfinder Azul', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_pathfinder3'               => ['name' => 'Nissan Pathfinder Rojo', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Suburban2015_n'                   => ['name' => 'POP Chevy Suburban 2015 Negro', 'price' => 318000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Youkun2015_b'                     => ['name' => 'POP GMC Yokun Denali 2015 Blanco', 'price' => 318000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Suburban2015_r'                   => ['name' => 'POP Chevy Suburban 2015 Rojo', 'price' => 318000, 'side' => 'civ', 'type' => 'Car'],
        'pop_landcruiser'                      => ['name' => 'POP Toyota Land Cruiser Negro', 'price' => 318000, 'side' => 'civ', 'type' => 'Car'],
        'pop_AudiQ7_r'                         => ['name' => 'POP Audi Q7 Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_13G65_r'                          => ['name' => 'POP Mercedes G65 2013 Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_HummerH2_r'                       => ['name' => 'POP HummerH2 Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_HummerH1_r'                       => ['name' => 'POP Hummer H1 Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_F350_r'                           => ['name' => 'POP Ford F350 Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_F150_r'                           => ['name' => 'POP Ford F150 Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Explorer_r'                       => ['name' => 'POP Ford Explorer Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_MercedesBenz6x6_r'                => ['name' => 'POP Mercedes Benz G63 6x6', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_patrol_corto'              => ['name' => 'Nissan Patrol Corto', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_S331_morada'                      => ['name' => 'POP Saleen S331 Morada', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_x52'                          => ['name' => 'BMW X5 Azul', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_x53'                          => ['name' => 'BMW X5 Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_hyundai_veloster2'                => ['name' => 'Hyundai Veloster Azul', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_hyundai_veloster3'                => ['name' => 'Hyundai Veloster Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_tahoe_r'                          => ['name' => 'POP Chevy Tahoe 2008 Rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_S331_r'                           => ['name' => 'POP Saleen S331 rojo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_escalade'                         => ['name' => 'POP Cadillac Escalade', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ_equipoa'              => ['name' => 'GMC Vandura Equipo A', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_noir'              => ['name' => 'Peugeot 508  Negro', 'price' => 33000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_bleufonce'         => ['name' => 'Peugeot 508  Azul Fuerte', 'price' => 33000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_rouge'             => ['name' => 'Peugeot 508  Rojo', 'price' => 33000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_jaune'             => ['name' => 'Peugeot 508  Amarillo', 'price' => 33000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_rose'              => ['name' => 'Peugeot 508  Rosa', 'price' => 33000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_grise'             => ['name' => 'Peugeot 508  Gris', 'price' => 33000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_violet'            => ['name' => 'Peugeot 508  Violeta', 'price' => 33000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_orange'            => ['name' => 'Peugeot 508  Naranja', 'price' => 33000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_noir_t'            => ['name' => 'Peugeot 508  Negro T', 'price' => 33000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_bleufonce_t'       => ['name' => 'Peugeot 508  Azul Fuerte T', 'price' => 39000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_rouge_t'           => ['name' => 'Peugeot 508  Rojo T', 'price' => 39000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_jaune_t'           => ['name' => 'Peugeot 508  Amarillo T', 'price' => 39000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_rose_t'            => ['name' => 'Peugeot 508  Rosa T', 'price' => 39000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_grise_t'           => ['name' => 'Peugeot 508  Gris T', 'price' => 39000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_violet_t'          => ['name' => 'Peugeot 508  Violeta T', 'price' => 39000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ_orange_t'          => ['name' => 'Peugeot 508  Naranja T', 'price' => 39000, 'side' => 'civ', 'type' => 'Car'],
        'pop_peugeot508_civ'                   => ['name' => 'Peugeot 508', 'price' => 39000, 'side' => 'civ', 'type' => 'Car'],
        'pop_alfa_romeo_159_azul'              => ['name' => 'Alfa Romeo 159 (Azul)', 'price' => 42000, 'side' => 'civ', 'type' => 'Car'],
        'pop_seat_ibiza_azul'                  => ['name' => 'Seat Ibiza Coupra (Azul Mate)', 'price' => 48000, 'side' => 'civ', 'type' => 'Car'],
        'pop_seat_ibiza_rojo'                  => ['name' => 'Seat Ibiza Coupra (Rojo Mate)', 'price' => 48000, 'side' => 'civ', 'type' => 'Car'],
        'pop_clio_civ'                         => ['name' => 'Clio RS', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_clio_civ_noir'                    => ['name' => 'Clio RS  Negro', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_clio_civ_bleufonce'               => ['name' => 'Clio RS Azul', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_clio_civ_rouge'                   => ['name' => 'Clio RS  Rojo', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_clio_civ_jaune'                   => ['name' => 'Clio RS  Amarillo', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_clio_civ_rose'                    => ['name' => 'Clio RS  Rosa', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_clio_civ_grise'                   => ['name' => 'Clio RS  Gris', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_clio_civ_violet'                  => ['name' => 'Clio RS  Violeta', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_clio_civ_orange'                  => ['name' => 'Clio RS  Naranja', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_ford_focusrs_azul'                => ['name' => 'Ford Focus RS (Azul)', 'price' => 60000, 'side' => 'civ', 'type' => 'Car'],
        'pop_ford_focusrs_rojo'                => ['name' => 'Ford Focus RS (Rojo)', 'price' => 60000, 'side' => 'civ', 'type' => 'Car'],
        'pop_seat_leon_azul'                   => ['name' => 'Seat Leon (Azul)', 'price' => 64500, 'side' => 'civ', 'type' => 'Car'],
        'pop_seat_leon_rojo'                   => ['name' => 'Seat Leon (Rojo)', 'price' => 64500, 'side' => 'civ', 'type' => 'Car'],
        'pop_astra_RS'                         => ['name' => 'Opel Astra RS', 'price' => 75000, 'side' => 'civ', 'type' => 'Car'],
        'pop_AudiA1_blanco'                    => ['name' => 'Audi A1 Quattro', 'price' => 82500, 'side' => 'civ', 'type' => 'Car'],
        'pop_AudiA1_D3'                        => ['name' => 'Audi A1 Quattro Sport 3', 'price' => 82500, 'side' => 'civ', 'type' => 'Car'],
        'pop_AudiA1_D2'                        => ['name' => 'Audi A1 Quattro Sport 2', 'price' => 82500, 'side' => 'civ', 'type' => 'Car'],
        'pop_AudiA1_D5'                        => ['name' => 'Audi A1 Quattro Sport 5', 'price' => 82500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Caprice1968_r'                    => ['name' => 'POP Chevy Caprice 1986 Rojo', 'price' => 90000, 'side' => 'civ', 'type' => 'Car'],
        'pop_69Charger_r'                      => ['name' => 'POP Dodge Charger 1969 Rojo', 'price' => 93000, 'side' => 'civ', 'type' => 'Car'],
        'POP_renaultmagnum1_f'                 => ['name' => 'Camion Renault Sin Caja', 'price' => 123000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Man_TGXsin_negro'                 => ['name' => 'Man TGX Sin Caja', 'price' => 114000, 'side' => 'civ', 'type' => 'Car'],
        'pop_volvo_camion_sin'                 => ['name' => 'Volvo Camion Sin Caja', 'price' => 105000, 'side' => 'civ', 'type' => 'Car'],
        'C_Van_01_fuel_F'                      => ['name' => 'Camión de combustible', 'price' => 75000, 'side' => 'civ', 'type' => 'Car'],
        'Volvo_Cisterna_1'                     => ['name' => 'Volvo Cisterna', 'price' => 157500, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_rojo_oscuro'          => ['name' => 'DAF XF Euro6 Rojo Oscuro', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_verde'                => ['name' => 'DAF XF Euro6 Verde', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_verde_oscuro'         => ['name' => 'DAF XF Euro6 Verde Oscuro', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_blanco'               => ['name' => 'DAF XF Euro6 Blanco', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_azul'                 => ['name' => 'DAF XF Euro6 Azul', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_azul_oscuro'          => ['name' => 'DAF XF Euro6 Azul Oscuro', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_gris'                 => ['name' => 'DAF XF Euro6 Gris', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_amarillo'             => ['name' => 'DAF XF Euro6 Amarillo', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_rosa'                 => ['name' => 'DAF XF Euro6 Rosa', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_violeta'              => ['name' => 'DAF XF Euro6 Violeta', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mercedes_vito'                    => ['name' => 'Mercedes Vito Azul', 'price' => 150000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mercedes_vito1'                   => ['name' => 'Mercedes Vito Roja', 'price' => 150000, 'side' => 'civ', 'type' => 'Car'],
        'pop_renault_master'                   => ['name' => 'Renault Master Azul', 'price' => 150000, 'side' => 'civ', 'type' => 'Car'],
        'pop_renault_master1'                  => ['name' => 'Renault Master Roja', 'price' => 150000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ'                      => ['name' => 'GMG Vandura', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ_negro'                => ['name' => 'GMG Vandura Negro', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ_azul'                 => ['name' => 'GMG Vandura Azul', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ_rojo'                 => ['name' => 'GMG Vandura Rojo', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ_Amarillo'             => ['name' => 'GMG Vandura Amarillo', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ_rosa'                 => ['name' => 'GMG Vandura Rosa', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ_gris'                 => ['name' => 'GMG Vandura Gris', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ_violeta'              => ['name' => 'GMG Vandura Violeta', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Vandura_civ_naranja'              => ['name' => 'GMG Vandura Naranja', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_a3_spr_civ_noir'              => ['name' => 'Mercedes Sprinter Negro', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_a3_spr_civ_bleufonce'         => ['name' => 'Mercedes Sprinter Azul', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_a3_spr_civ_rouge'             => ['name' => 'Mercedes Sprinter Rojo', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_a3_spr_civ_jaune'             => ['name' => 'Mercedes Sprinter Amarillo', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_a3_spr_civ_rose'              => ['name' => 'Mercedes Sprinter Rosa', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_a3_spr_civ_grise'             => ['name' => 'Mercedes Sprinter Gris', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_a3_spr_civ_violet'            => ['name' => 'Mercedes Sprinter Violeta', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_a3_spr_civ_orange'            => ['name' => 'Mercedes Sprinter Naranja', 'price' => 397500, 'side' => 'civ', 'type' => 'Car'],
        'midlum_grey'                          => ['name' => 'Renault Midlum Gris', 'price' => 450000, 'side' => 'civ', 'type' => 'Car'],
        'midlum_yellow'                        => ['name' => 'Renault Midlum Amarillo', 'price' => 450000, 'side' => 'civ', 'type' => 'Car'],
        'midlum_blue'                          => ['name' => 'Renault Midlum Azul', 'price' => 450000, 'side' => 'civ', 'type' => 'Car'],
        'midlum_red'                           => ['name' => 'Renault Midlum Rojo', 'price' => 450000, 'side' => 'civ', 'type' => 'Car'],
        'pop_scania_r6202'                     => ['name' => 'Scania R620 Rojo', 'price' => 525000, 'side' => 'civ', 'type' => 'Car'],
        'pop_scania_r6203'                     => ['name' => 'Scania R620 Azul', 'price' => 525000, 'side' => 'civ', 'type' => 'Car'],
        'pop_volvo_camion'                     => ['name' => 'Volvo Camion', 'price' => 540000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Man_TGX_negro'                    => ['name' => 'Man TGX', 'price' => 600000, 'side' => 'civ', 'type' => 'Car'],
        'pop_iveco_f'                          => ['name' => 'Iveco', 'price' => 645000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_ivceco_bleufonce'             => ['name' => 'Iveco Azul Oscuro', 'price' => 705000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_ivceco_rouge'                 => ['name' => 'Iveco Rojo', 'price' => 705000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_ivceco_jaune'                 => ['name' => 'Iveco Amarillo', 'price' => 705000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_ivceco_rose'                  => ['name' => 'Iveco Rosa', 'price' => 705000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_ivceco_grise'                 => ['name' => 'Iveco Gris', 'price' => 705000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_ivceco_orange'                => ['name' => 'Iveco Naranja', 'price' => 705000, 'side' => 'civ', 'type' => 'Car'],
        'dikeman_haulier2'                     => ['name' => 'Dikeman Haulier Rojo', 'price' => 795000, 'side' => 'civ', 'type' => 'Car'],
        'dikeman_haulier3'                     => ['name' => 'Dikeman Haulier Azul', 'price' => 795000, 'side' => 'civ', 'type' => 'Car'],
        'O_Lifeboat'                           => ['name' => 'Bote salvavidas', 'price' => 3750, 'side' => 'med', 'type' => 'Ship'],
        'C_Boat_Civil_01_rescue_F'             => ['name' => 'Lancha motora (rescate)', 'price' => 3750, 'side' => 'med', 'type' => 'Ship'],
        'ec135_policia_f'                      => ['name' => 'Airbus HC EC135 - Policia Nacional', 'price' => 11250, 'side' => 'civ', 'type' => 'Car'],
        'ec135_guardiacivil_F'                 => ['name' => 'Airbus HC EC135 - Guardia Civil', 'price' => 11250, 'side' => 'civ', 'type' => 'Car'],
        'bo_105_policia_F'                     => ['name' => 'MBB BO 105 - Policia Nacional', 'price' => 9000, 'side' => 'civ', 'type' => 'Car'],
        'bo_105_guardiacivil_F'                => ['name' => 'MBB BO 105 - Guardia Civil', 'price' => 9000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_1200_rt_atgc_atgc'            => ['name' => 'BMW 1150RT ATGC', 'price' => 7500, 'side' => 'cop', 'type' => 'Car'],
        'pop_alfa_romeo_159_atgc1'             => ['name' => 'Alfa Romeo 159 ATGC', 'price' => 9000, 'side' => 'cop', 'type' => 'Car'],
        'pop_jeep_grand_cherokee_atgc1'        => ['name' => 'Jeep Grand Cherokee ATGC', 'price' => 10500, 'side' => 'cop', 'type' => 'Car'],
        'pop_mitsubishi_asx_atgc'              => ['name' => 'Mitsubishi ASX ATGC', 'price' => 6000, 'side' => 'cop', 'type' => 'Car'],
        'pop_mitsubishi_montero_atgc1'         => ['name' => 'Mitsubishi Montero ATGC', 'price' => 6000, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_pathfinder_atgc'           => ['name' => 'Nissan Pathfinder ATGC', 'price' => 4500, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_qashqai_atgc1'             => ['name' => 'Nissan Qashqai ATGC', 'price' => 5250, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_xtrail_policia2'           => ['name' => 'Nissan Xtrail ATGC', 'price' => 6000, 'side' => 'cop', 'type' => 'Car'],
        'pop_opel_insignia_atgc1'              => ['name' => 'Opel Insignia ATGC', 'price' => 7500, 'side' => 'cop', 'type' => 'Car'],
        'pop_peugeot_407_atgc1'                => ['name' => 'Peugeot 407 ATGC', 'price' => 1500, 'side' => 'cop', 'type' => 'Car'],
        'pop_toyota_camry_atgc1'               => ['name' => 'Toyota Camry ATGC', 'price' => 9000, 'side' => 'cop', 'type' => 'Car'],
        'pop_toyota_prado_atgc'                => ['name' => 'Toyota Prado ATGC', 'price' => 4500, 'side' => 'cop', 'type' => 'Car'],
        'pop_mercedes_sprinter_corta_atgc1'    => ['name' => 'Mercedes Benz Sprinter Corta ATGC', 'price' => 7500, 'side' => 'cop', 'type' => 'Car'],
        'pop_mercedes_benz_vito_atgc1'         => ['name' => 'Mercedes Benz Vito ATGC', 'price' => 7500, 'side' => 'cop', 'type' => 'Car'],
        'pop_citroen_c4_gc1'                   => ['name' => 'Citroen C4 GC', 'price' => 2250, 'side' => 'cop', 'type' => 'Car'],
        'pop_citroen_c4_picasso_2016_gc1'      => ['name' => 'Citroen C4 Picasso 2016 GC', 'price' => 3000, 'side' => 'cop', 'type' => 'Car'],
        'pop_citroen_c4_picasso_gc1'           => ['name' => 'Citroen C4 Picasso GC', 'price' => 1500, 'side' => 'cop', 'type' => 'Car'],
        'pop_fiat_bravo_gc1'                   => ['name' => 'Fiat Bravo GC', 'price' => 3750, 'side' => 'cop', 'type' => 'Car'],
        'pop_honda_crv_gc1'                    => ['name' => 'Honda CRV GC', 'price' => 6000, 'side' => 'cop', 'type' => 'Car'],
        'pop_land_rover_freelander_gc1'        => ['name' => 'Land Rover Freelander GC', 'price' => 5250, 'side' => 'cop', 'type' => 'Car'],
        'pop_mitsubishi_asx_gc1'               => ['name' => 'Mitsubishi ASX GC', 'price' => 4500, 'side' => 'cop', 'type' => 'Car'],
        'pop_mitsubishi_montero_gc1'           => ['name' => 'Mitsubishi Montero GC', 'price' => 7500, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_pathfinder_gc'             => ['name' => 'Nissan Pathfinder GC', 'price' => 5250, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_patrol_gc1'                => ['name' => 'Nissan Patrol GC', 'price' => 6000, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_qashqai_2016_policia1'     => ['name' => 'Nissan Qashqai 2016 GC', 'price' => 9000, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_xtrail_policia1'           => ['name' => 'Nissan Xtrail GC', 'price' => 6000, 'side' => 'cop', 'type' => 'Car'],
        'pop_opel_astra_h_gc1'                 => ['name' => 'Opel Astra H GC', 'price' => 1500, 'side' => 'cop', 'type' => 'Car'],
        'pop_opel_astra_j_gc1'                 => ['name' => 'Opel Astra J GC', 'price' => 4500, 'side' => 'cop', 'type' => 'Car'],
        'pop_peugeot_308_gc1'                  => ['name' => 'Peugeot 308 GC', 'price' => 6000, 'side' => 'cop', 'type' => 'Car'],
        'pop_peugeot_406_gc1'                  => ['name' => 'Peugeot 406 GC', 'price' => 2250, 'side' => 'cop', 'type' => 'Car'],
        'pop_renault_megane_ii_gc1'            => ['name' => 'Renault Megane II GC', 'price' => 3000, 'side' => 'cop', 'type' => 'Car'],
        'pop_toyota_prado_gc1'                 => ['name' => 'Toyota Prado GC', 'price' => 7500, 'side' => 'cop', 'type' => 'Car'],
        'pop_yamaha_xt660r_cnp_atgc'           => ['name' => 'Yamaha XT660R CNP', 'price' => 7500, 'side' => 'cop', 'type' => 'Car'],
        'pop_citroen_c4_picasso_2016_cnp1'     => ['name' => 'Citroen C4 Picasso 2016 CNP', 'price' => 3000, 'side' => 'cop', 'type' => 'Car'],
        'pop_citroen_c4_picasso_cnp1'          => ['name' => 'Citroen C4 Picasso CNP', 'price' => 1500, 'side' => 'cop', 'type' => 'Car'],
        'pop_citroen_xsara_picasso_cnp1'       => ['name' => 'Citroen C4 Xsara Picasso CNP', 'price' => 2250, 'side' => 'cop', 'type' => 'Car'],
        'pop_citroen_xsara_picasso_cnp2'       => ['name' => 'Citroen C4 Xsara Picasso CNP (Casa Real)', 'price' => 2250, 'side' => 'cop', 'type' => 'Car'],
        'pop_mercedes_benz_vito_cnp1'          => ['name' => 'Mercedes Benz Vito CNP', 'price' => 5250, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_patrol_cnp1'               => ['name' => 'Nissan Patrol CNP', 'price' => 6000, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_qashqai_2016_policia3'     => ['name' => 'Nissan Qashqai 2016 CNP', 'price' => 9000, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_qashqai_cnp1'              => ['name' => 'Nissan Qashqai CNP', 'price' => 5250, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_xtrail_policia3'           => ['name' => 'Nissan Xtrail CNP', 'price' => 6000, 'side' => 'cop', 'type' => 'Car'],
        'pop_opel_vivaro_cnp1'                 => ['name' => 'Opel Vivaro CNP', 'price' => 300, 'side' => 'cop', 'type' => 'Car'],
        'pop_autocar_presos'                   => ['name' => 'Autocar Presos GC', 'price' => 1500, 'side' => 'cop', 'type' => 'Car'],
        'pop_mercedes_sprinter_corta_policia1' => ['name' => 'Mercedes Benz Sprinter Corta CNP', 'price' => 4500, 'side' => 'cop', 'type' => 'Car'],
        'pop_mercedes_sprinter_corta_policia2' => ['name' => 'Mercedes Benz Sprinter Corta GC', 'price' => 4500, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_pathfinder_uip1'           => ['name' => 'Nissan Pathfinder UIP', 'price' => 3750, 'side' => 'cop', 'type' => 'Car'],
        'pop_nissan_pathfinder_gar'            => ['name' => 'Nissan Pathfinder GAR', 'price' => 3750, 'side' => 'cop', 'type' => 'Car'],
        'pop_toyota_prado_gar'                 => ['name' => 'Toyota Prado GAR', 'price' => 4500, 'side' => 'cop', 'type' => 'Car'],
        'pop_camion_antidisturbios1'           => ['name' => 'Camion Antidisturbios CNP', 'price' => 5250, 'side' => 'cop', 'type' => 'Car'],
        'pop_hummer_geo_camuflado'             => ['name' => 'POP Hummer H2 Negro', 'price' => 9750, 'side' => 'cop', 'type' => 'Car'],
        'pop_chrysler_camuflado'               => ['name' => 'POP Chrysler 300C Negro', 'price' => 9750, 'side' => 'cop', 'type' => 'Car'],
        'pop_audiq7_camuflado'                 => ['name' => 'POP Audi Q7 Negro', 'price' => 9750, 'side' => 'cop', 'type' => 'Car'],
        'pop_audi_a1_camuflado'                => ['name' => 'Audi A1 Quattro', 'price' => 9750, 'side' => 'cop', 'type' => 'Car'],
        'gazelle_civil_1'                      => ['name' => 'Gazelle SA 342 (Blanco)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'gazelle_civil_2'                      => ['name' => 'Gazelle SA 342 (Negro)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'gazelle_civil_3'                      => ['name' => 'Gazelle SA 342 (POPTV)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'ec135_popnews_F'                      => ['name' => 'Airbus HC EC135 - POP News', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_red_F'              => ['name' => 'M-900 (Red)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_ion_F'              => ['name' => 'M-900 (ION)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_blueLine_F'         => ['name' => 'M-900 (BlueLine)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_digital_F'          => ['name' => 'M-900 (Digital)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_elliptical_F'       => ['name' => 'M-900 (Elliptical)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_furious_F'          => ['name' => 'M-900 (Furious)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_graywatcher_F'      => ['name' => 'M-900 (GrayWatcher)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_jeans_F'            => ['name' => 'M-900 (Jeans)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_light_F'            => ['name' => 'M-900 (Light)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_shadow_F'           => ['name' => 'M-900 (Shadow)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_sheriff_F'          => ['name' => 'M-900 (Sheriff)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_speedy_F'           => ['name' => 'M-900 (Speedy)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_sunset_F'           => ['name' => 'M-900 (Sunset)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_vrana_F'            => ['name' => 'M-900 (VRANA)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_wasp_F'             => ['name' => 'M-900 (Wasp)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_wave_F'             => ['name' => 'M-900 (Wave)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_camuflaje_F'        => ['name' => 'M-900 (Camuflaje)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_naranja_F'          => ['name' => 'M-900 (Naranja)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_chapa_F'            => ['name' => 'M-900 (Chapa)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_escamas_F'          => ['name' => 'M-900 (Escamas)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_olas_F'             => ['name' => 'M-900 (Olas)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_pelotas_F'          => ['name' => 'M-900 (Pelotas)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_psico1_F'           => ['name' => 'M-900 (Psyco1)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_psico2_F'           => ['name' => 'M-900 (Psyco2)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_psico3_F'           => ['name' => 'M-900 (Psyco3)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_psico4_F'           => ['name' => 'M-900 (Psyco4)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_psico5_F'           => ['name' => 'M-900 (Psyco5)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_amanecer_F'         => ['name' => 'M-900 (Amanecer)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_triangulos_F'       => ['name' => 'M-900 (Triangulos)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'pop_heli_Light_01_triangulos2_F'      => ['name' => 'M-900 (Triangulos2)', 'price' => 1050000, 'side' => 'civ', 'type' => 'Air'],
        'ec135_civil_rojo'                     => ['name' => 'Airbus HC EC135 - Civil Rojo', 'price' => 1200000, 'side' => 'civ', 'type' => 'Air'],
        'ec135_civil_blanco'                   => ['name' => 'Airbus HC EC135 - Civil Blanco', 'price' => 1200000, 'side' => 'civ', 'type' => 'Air'],
        'ec135_civil_azul'                     => ['name' => 'Airbus HC EC135 - Civil Azul', 'price' => 1200000, 'side' => 'civ', 'type' => 'Air'],
        'ec135_civil_Negro'                    => ['name' => 'Airbus HC EC135 - Civil Negro', 'price' => 1200000, 'side' => 'civ', 'type' => 'Air'],
        'frogger_civil_3'                      => ['name' => 'Frogger (Azul)', 'price' => 1200000, 'side' => 'civ', 'type' => 'Air'],
        'frogger_civil_4'                      => ['name' => 'Frogger (Rojo)', 'price' => 1200000, 'side' => 'civ', 'type' => 'Air'],
        'C_Boat_Civil_01_police_F'             => ['name' => 'Lancha motora (policía)', 'price' => 3000, 'side' => 'civ', 'type' => 'Car'],
        'B_Boat_Transport_01_F'                => ['name' => 'Bote de asalto', 'price' => 4500, 'side' => 'civ', 'type' => 'Car'],
        'pop_predator'                         => ['name' => 'Predator GC', 'price' => 4500, 'side' => 'civ', 'type' => 'Car'],
        'C_Rubberboat'                         => ['name' => 'Bote salvavidas', 'price' => 1800, 'side' => 'civ', 'type' => 'Ship'],
        'POP_Speed_yatch'                      => ['name' => 'Yate de lujo', 'price' => 225000, 'side' => 'civ', 'type' => 'Ship'],
        'pop_pesca'                            => ['name' => 'Barco de pesca', 'price' => 225000, 'side' => 'civ', 'type' => 'Ship'],
        'pop_insurgent_v1'                     => ['name' => 'Vehiculo Insurgente Blanco', 'price' => 165000, 'side' => 'civ', 'type' => 'Car'],
        'pop_insurgent_vELN'                   => ['name' => 'Vehiculo Insurgente ELN', 'price' => 165000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_gustav'                => ['name' => 'Megane GT3 Gustav VIP', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_silvia'                    => ['name' => 'Nissan silvia Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_silvia1'                   => ['name' => 'Nissan silvia Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_silvia4'                   => ['name' => 'Nissan silvia Top Secret', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_JaguarP7Civil'                    => ['name' => 'Jaguar F-Type Project 7', 'price' => 187500, 'side' => 'civ', 'type' => 'Car'],
        'pop_hyundai_veloster'                 => ['name' => 'Hyundai Veloster Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_hyundai_veloster1'                => ['name' => 'Hyundai Veloster Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_ford_gt40'                        => ['name' => 'Ford GT40 Negro', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_ford_gt401'                       => ['name' => 'Ford GT40 Blanco', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_ford_gt404'                       => ['name' => 'Ford GT40 Amarillo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_488GT3Civil'                      => ['name' => 'Ferrari 488 GT3', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_x5'                           => ['name' => 'BMW X5 Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw_x51'                          => ['name' => 'BMW X5 Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_camaro_vip_david'       => ['name' => 'Chevrolet Camaro ZL1 (Vip David Martin)', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_camaro_blanco'          => ['name' => 'Chevrolet Camaro ZL1 (Blanco)', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_camaro_negro'           => ['name' => 'Chevrolet Camaro ZL1 (Negro)', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_pathfinder'                => ['name' => 'Nissan Pathfinder Negro', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_pathfinder1'               => ['name' => 'Nissan Pathfinder Blanco', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_skyline'                   => ['name' => 'Nissan Skyline Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_skyline1'                  => ['name' => 'Nissan Skyline Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_seat_leon_negro'                  => ['name' => 'Seat Leon (Negro)', 'price' => 64500, 'side' => 'civ', 'type' => 'Car'],
        'pop_ford_focusrs_verde'               => ['name' => 'Ford Focus RS (verde)', 'price' => 60000, 'side' => 'civ', 'type' => 'Car'],
        'pop_ford_focusrs_negro'               => ['name' => 'Ford Focus RS (Negro)', 'price' => 60000, 'side' => 'civ', 'type' => 'Car'],
        'pop_ford_focusrs_blanco'              => ['name' => 'Ford Focus RS (Blanco)', 'price' => 60000, 'side' => 'civ', 'type' => 'Car'],
        'pop_seat_ibiza_blanco'                => ['name' => 'Seat Ibiza Coupra (Blanco Mate)', 'price' => 48000, 'side' => 'civ', 'type' => 'Car'],
        'pop_seat_ibiza_negro'                 => ['name' => 'Seat Ibiza Coupra (Negro Mate)', 'price' => 48000, 'side' => 'civ', 'type' => 'Car'],
        'pop_alfa_romeo_159_negro'             => ['name' => 'Alfa Romeo 159 (Negro)', 'price' => 42000, 'side' => 'civ', 'type' => 'Car'],
        'pop_alfa_romeo_159_rojo'              => ['name' => 'Alfa Romeo 159 (Rojo)', 'price' => 42000, 'side' => 'civ', 'type' => 'Car'],
        'pop_AudiA1_D4'                        => ['name' => 'Audi A1 Quattro Sport 4', 'price' => 82500, 'side' => 'civ', 'type' => 'Car'],
        'pop_AudiA1_D1'                        => ['name' => 'Audi A1 Quattro Sport 1', 'price' => 82500, 'side' => 'civ', 'type' => 'Car'],
        'pop_daciaCivil'                       => ['name' => 'Dacia Buster Terrorista', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mercedes_vito2'                   => ['name' => 'Mercedes Vito blanca', 'price' => 150000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mercedes_vito3'                   => ['name' => 'Mercedes Vito Negra', 'price' => 150000, 'side' => 'civ', 'type' => 'Car'],
        'pop_amg_GT1'                          => ['name' => 'Mercedes AMG GT', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_amg_GT_blanco'                    => ['name' => 'Mercedes AMG GT Blanco', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'PKE_92_civ_noir'                      => ['name' => 'Porsche 911 92  Negro', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'PKE_92_civ_rouge'                     => ['name' => 'Porsche 911 92  Rojo', 'price' => 52500, 'side' => 'civ', 'type' => 'Car'],
        'pop_370Z1'                            => ['name' => 'Nissan 370Z', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_370Z_blanco'                      => ['name' => 'Nissan 370Z Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_afla_4C_rojo'                     => ['name' => 'Alfa Romeo 4C Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_afla_4C_negro'                    => ['name' => 'Alfa Romeo 4C Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_afla_4C_amarillo'                 => ['name' => 'Alfa Romeo 4C Amarillo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_afla_4C_naranja'                  => ['name' => 'Alfa Romeo 4C', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lotus_GTE_naranja'                => ['name' => 'Lotus Evora GTE', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lotus_GTE_rojo'                   => ['name' => 'Lotus Evora GTE Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_caymanS_z_blanco'                 => ['name' => 'Porsche Cayman Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevroletc7_rojo'                 => ['name' => 'Chevrolet Corvette Stingray C7 rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevroletc7_negro'                => ['name' => 'Chevrolet Corvette Stingray C7 negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevroletc7_blanco'               => ['name' => 'Chevrolet Corvette Super Sport blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_regera_negro'                     => ['name' => 'Koenigsegg Regera negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_regera_rojo'                      => ['name' => 'Koenigsegg Regera rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw507_d'                         => ['name' => 'Bmw 507 negro mate', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw8'                             => ['name' => 'BMW I8', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmw8_blanco'                      => ['name' => 'BMW I8 Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_m300sl3'                          => ['name' => 'Mercedes-Benz 300 SL Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_laferrari_negro'                  => ['name' => 'Ferrari LaFerrari Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_chevrolet_rojo'                   => ['name' => 'Chevrolet Corvette Super Sport rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_InsurgentCivil'                   => ['name' => 'Blindado', 'price' => 517500, 'side' => 'civ', 'type' => 'Car'],
        'pop_toyota_FJCruiser'                 => ['name' => 'Toyota FJCruiser Negro', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_toyota_FJCruiser1'                => ['name' => 'Toyota FJCruiser Blanco', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_qashqai'                   => ['name' => 'Nissan Qashqai Negro', 'price' => 247500, 'side' => 'civ', 'type' => 'Car'],
        'pop_nissan_qashqai1'                  => ['name' => 'Nissan Qashqai Blanco', 'price' => 247500, 'side' => 'civ', 'type' => 'Car'],
        'pop_jeep_grandcherokee'               => ['name' => 'Jeep Grand Cherokee Negro', 'price' => 285000, 'side' => 'civ', 'type' => 'Car'],
        'pop_jeep_grandcherokee1'              => ['name' => 'Jeep Grand Cherokee Blanco', 'price' => 285000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lexus_gx4601'                     => ['name' => 'Lexus Gx460 Blanco', 'price' => 292500, 'side' => 'civ', 'type' => 'Car'],
        'pop_volvo'                            => ['name' => 'Volvo Xc90 Negro', 'price' => 195000, 'side' => 'civ', 'type' => 'Car'],
        'pop_volvo1'                           => ['name' => 'Volvo Xc90 Blanco', 'price' => 195000, 'side' => 'civ', 'type' => 'Car'],
        'pop_volvo3'                           => ['name' => 'Volvo Xc90 Rojo', 'price' => 195000, 'side' => 'civ', 'type' => 'Car'],
        'pop_hyundai_x35'                      => ['name' => 'Hyundai X35 Negro', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_hyundai_x351'                     => ['name' => 'Hyundai X35 Blanco', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_hyundai_x353'                     => ['name' => 'Hyundai X35 Rojo', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_rover_evo_negro'                  => ['name' => 'Range Rover Evoque Negro', 'price' => 232500, 'side' => 'civ', 'type' => 'Car'],
        'pop_rover_evo_naranja'                => ['name' => 'Range Rover Evoque Naranja', 'price' => 232500, 'side' => 'civ', 'type' => 'Car'],
        'pop_ranger_rover'                     => ['name' => 'Range Rover Negro', 'price' => 232500, 'side' => 'civ', 'type' => 'Car'],
        'pop_ranger_rover1'                    => ['name' => 'Range Rover Blanco', 'price' => 232500, 'side' => 'civ', 'type' => 'Car'],
        'pop_ranger_rover2'                    => ['name' => 'Range Rover Azul', 'price' => 232500, 'side' => 'civ', 'type' => 'Car'],
        'pop_rover_evo_rojo'                   => ['name' => 'Range Rover Evoque Rojo', 'price' => 232500, 'side' => 'civ', 'type' => 'Car'],
        'shounka_ivceco_noir'                  => ['name' => 'Iveco  Noir', 'price' => 705000, 'side' => 'civ', 'type' => 'Car'],
        'pop_scania_r620'                      => ['name' => 'Scania R620 Negro', 'price' => 525000, 'side' => 'civ', 'type' => 'Car'],
        'pop_scania_r6201'                     => ['name' => 'Scania R620 Blanco', 'price' => 525000, 'side' => 'civ', 'type' => 'Car'],
        'dikeman_haulier'                      => ['name' => 'Dikeman Haulier Negro', 'price' => 795000, 'side' => 'civ', 'type' => 'Car'],
        'dikeman_haulier1'                     => ['name' => 'Dikeman Haulier Blanco', 'price' => 795000, 'side' => 'civ', 'type' => 'Car'],
        'midlum'                               => ['name' => 'Renault Midlum', 'price' => 450000, 'side' => 'civ', 'type' => 'Car'],
        'midlum_black'                         => ['name' => 'Renault Midlum Noir', 'price' => 450000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_rojo'                 => ['name' => 'DAF XF EURO6 (Rojo)', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_dafxf_euro6_negro'                => ['name' => 'DAF XF EURO6 (Negro)', 'price' => 120000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lola_10'                          => ['name' => 'Aston Martin DBR1-2 10', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_lola_3'                           => ['name' => 'Aston Martin DBR1-2 3', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_16'                    => ['name' => 'Megane GT3 16', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_38'                    => ['name' => 'Megane GT3 38', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_36'                    => ['name' => 'Megane GT3 36', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_34'                    => ['name' => 'Megane GT3 34', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_24'                    => ['name' => 'Megane GT3 24', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_1'                     => ['name' => 'Megane GT3 1', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_5'                     => ['name' => 'Megane GT3 5', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_3'                     => ['name' => 'Megane GT3 3', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_4'                     => ['name' => 'Megane GT3 4', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_6'                     => ['name' => 'Megane GT3 6', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_7'                     => ['name' => 'Megane GT3 7', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_8'                     => ['name' => 'Megane GT3 8', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_9'                     => ['name' => 'Megane GT3 9', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_10'                    => ['name' => 'Megane GT3 10', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_11'                    => ['name' => 'Megane GT3 11', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_12'                    => ['name' => 'Megane GT3 12', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_13'                    => ['name' => 'Megane GT3 13', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_14'                    => ['name' => 'Megane GT3 14', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_15'                    => ['name' => 'Megane GT3 15', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_18'                    => ['name' => 'Megane GT3 18', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_19'                    => ['name' => 'Megane GT3 19', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_20'                    => ['name' => 'Megane GT3 20', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_22'                    => ['name' => 'Megane GT3 22', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_23'                    => ['name' => 'Megane GT3 23', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_25'                    => ['name' => 'Megane GT3 25', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_26'                    => ['name' => 'Megane GT3 26', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_27'                    => ['name' => 'Megane GT3 27', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_28'                    => ['name' => 'Megane GT3 28', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_29'                    => ['name' => 'Megane GT3 29', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_30'                    => ['name' => 'Megane GT3 30', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_31'                    => ['name' => 'Megane GT3 31', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_32'                    => ['name' => 'Megane GT3 32', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_33'                    => ['name' => 'Megane GT3 33', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_35'                    => ['name' => 'Megane GT3 35', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_megane_GT3_37'                    => ['name' => 'Megane GT3 37', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_GT3_negro'                        => ['name' => 'Nissan GT-R Nismo GT3 Sport Negro', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Caterham_1'                       => ['name' => 'Caterham R500 Rojo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Caterham_4'                       => ['name' => 'Caterham R500 Verde', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mono_D1'                          => ['name' => 'BAC Sport 1', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mono_D2'                          => ['name' => 'BAC Sport 2', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mono_D3'                          => ['name' => 'BAC Sport 3', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_mono_D4'                          => ['name' => 'BAC Sport 4', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_r8MP_2'                           => ['name' => 'Audi R8 LMP900 3', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_r8MP_6'                           => ['name' => 'Audi R8 LMP900 7', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_r8MP_7'                           => ['name' => 'Audi R8 LMP900 8', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_limo_civ_noir'                => ['name' => 'Limousine Audi Negro', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_limo_civ_rouge'               => ['name' => 'Limousine Audi Rojo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'shounka_limo_civ_jaune'               => ['name' => 'Limousine Audi Amarillo', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_tahoe_b'                          => ['name' => 'POP Chevy Tahoe 2008 Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_tahoe_n'                          => ['name' => 'POP Chevy Tahoe 2008 Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Youkun2015_n'                     => ['name' => 'POP GMC Yokun Denali 2015 Negro', 'price' => 318000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Suburban2015_b'                   => ['name' => 'POP Chevy Suburban 2015 Blanco', 'price' => 318000, 'side' => 'civ', 'type' => 'Car'],
        'pop_S331_g'                           => ['name' => 'POP Saleen S331 blanco mate', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_S331_n'                           => ['name' => 'POP Saleen S331 negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_RollsRoycePH_n'                   => ['name' => 'POP Rolls Royce Phantom Negro 2000', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_RollsRoyce011_n'                  => ['name' => 'POP RollsRoyce Phantom negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_NissanGTR_b'                      => ['name' => 'POP Nissan GTR 2015 Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_MustangMach1Jet1969_b'            => ['name' => 'POP Mustang Mach1 Jet1969 Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_MercedesBenz6x6_n'                => ['name' => 'POP Mercedes Benz G63 6x6', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_MercedesBenz6x6_b'                => ['name' => 'POP Mercedes Benz G63 6x6', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_MaybachLaundet57_b'               => ['name' => 'POP Mercedes S 500 Blanco', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_landcruiser_b'                    => ['name' => 'POP Toyota Land Cruiser Blanco', 'price' => 318000, 'side' => 'civ', 'type' => 'Car'],
        'pop_JeepWrangler_b'                   => ['name' => 'POP Jeep Wrangler Blanco', 'price' => 127500, 'side' => 'civ', 'type' => 'Car'],
        'pop_JeepWrangler_n'                   => ['name' => 'POP Jeep Wrangler Negro', 'price' => 127500, 'side' => 'civ', 'type' => 'Car'],
        'pop_HummerH2'                         => ['name' => 'POP HummerH2 Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_HummerH2_b'                       => ['name' => 'POP HummerH2 Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_HummerH2_a'                       => ['name' => 'POP HummerH2 Amarillo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_HummerH1'                         => ['name' => 'POP Hummer H1 Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_HummerH1_b'                       => ['name' => 'POP Hummer H1 Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_HummerH1_a'                       => ['name' => 'POP Hummer H1 Amarillo', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_GMCSerriaLarge_b'                 => ['name' => 'GMC Blanco', 'price' => 277500, 'side' => 'civ', 'type' => 'Car'],
        'pop_GMCSerriaLarge_n'                 => ['name' => 'GMC Negro', 'price' => 277500, 'side' => 'civ', 'type' => 'Car'],
        'pop_F350_n'                           => ['name' => 'POP Ford F350 Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_F350_b'                           => ['name' => 'POP Ford F350 Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_F150_n'                           => ['name' => 'POP Ford F150 Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_F150_b'                           => ['name' => 'POP Ford F150 Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Explorer_n'                       => ['name' => 'POP Ford Explorer Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Explorer_b'                       => ['name' => 'POP Ford Explorer Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_Chrysler_n'                       => ['name' => 'POP Chrysler 300C Negro', 'price' => 74250, 'side' => 'civ', 'type' => 'Car'],
        'pop_Chrysler_b'                       => ['name' => 'POP Chrysler 300C Blanco', 'price' => 74250, 'side' => 'civ', 'type' => 'Car'],
        'pop_Charger_12_n'                     => ['name' => 'POP Dodge Charger 2012 Negro', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Charger_12_b'                     => ['name' => 'POP Dodge Charger 2012 Blanco', 'price' => 225000, 'side' => 'civ', 'type' => 'Car'],
        'pop_Caprice1968_b'                    => ['name' => 'POP Chevy Caprice 1986 Blanco', 'price' => 90000, 'side' => 'civ', 'type' => 'Car'],
        'pop_BMW750il_b'                       => ['name' => 'POP BMW 750 il Blanco', 'price' => 233250, 'side' => 'civ', 'type' => 'Car'],
        'pop_BMW750il_n'                       => ['name' => 'POP BMW 750 il Negro', 'price' => 233250, 'side' => 'civ', 'type' => 'Car'],
        'pop_AudiQ7_b'                         => ['name' => 'POP Audi Q7 Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_AudiQ7_n'                         => ['name' => 'POP Audi Q7 Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_300c_b'                           => ['name' => 'POP Chrysler 300C 2007', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_300c_n'                           => ['name' => 'POP Chrysler 300C 2007', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_69Charger_n'                      => ['name' => 'POP Dodge Charger 1969 Negro', 'price' => 93000, 'side' => 'civ', 'type' => 'Car'],
        'pop_69Charger_b'                      => ['name' => 'POP Dodge Charger 1969 Blanco', 'price' => 93000, 'side' => 'civ', 'type' => 'Car'],
        'pop_13G65_b'                          => ['name' => 'POP Mercedes G65 2013 Blanco', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_13G65_n'                          => ['name' => 'POP Mercedes G65 2013 Negro', 'price' => 322500, 'side' => 'civ', 'type' => 'Car'],
        'pop_renault_master2'                  => ['name' => 'Renault Master blanca', 'price' => 150000, 'side' => 'civ', 'type' => 'Car'],
        'pop_renault_master3'                  => ['name' => 'Renault Master Negra', 'price' => 150000, 'side' => 'civ', 'type' => 'Car'],
        'pop_honda_bizz_Negra'                 => ['name' => 'Honda Bizz Negra', 'price' => 74250, 'side' => 'civ', 'type' => 'Car'],
        'pop_honda_bizz_Blanca'                => ['name' => 'Honda Bizz Blanca', 'price' => 74250, 'side' => 'civ', 'type' => 'Car'],
        'pop_moto_1_negra'                     => ['name' => 'Bagger Negra', 'price' => 74250, 'side' => 'civ', 'type' => 'Car'],
        'pop_moto_1_blanca'                    => ['name' => 'Bagger Blanca', 'price' => 74250, 'side' => 'civ', 'type' => 'Car'],
        'pop_moto_2_blanca'                    => ['name' => 'Hexer Blanca', 'price' => 74250, 'side' => 'civ', 'type' => 'Car'],
        'frogger_civil_1'                      => ['name' => 'Frogger (Blanco)', 'price' => 1200000, 'side' => 'civ', 'type' => 'Car'],
        'frogger_civil_2'                      => ['name' => 'Frogger (Negro)', 'price' => 1200000, 'side' => 'civ', 'type' => 'Car'],
        'POP_veneno_blanco'                    => ['name' => 'Lamborghini Veneno Blanco Sport', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'POP_veneno_negro'                     => ['name' => 'Lamborghini Veneno Negro', 'price' => 900000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_negro'                      => ['name' => 'Bmw 6 Negro', 'price' => 675000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_gris'                       => ['name' => 'Bmw 6 Gris', 'price' => 675000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_azul'                       => ['name' => 'Bmw 6 Azul', 'price' => 675000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_rojo'                       => ['name' => 'Bmw 6 Rojo', 'price' => 675000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_amarillo'                   => ['name' => 'Bmw 6 Amarillo', 'price' => 675000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_rosa'                       => ['name' => 'Bmw 6 Rosa', 'price' => 675000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_violet'                     => ['name' => 'Bmw 6 Morado', 'price' => 675000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_naranja'                    => ['name' => 'Bmw 6 Naranja', 'price' => 675000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_azul_t'                     => ['name' => 'Bmw 6 Azul', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_rojo_t'                     => ['name' => 'Bmw 6 Rojo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_amarillo_t'                 => ['name' => 'Bmw 6 Amarillo', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_rosa_t'                     => ['name' => 'Bmw 6 Rosa', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_violet_t'                   => ['name' => 'Bmw 6 Morado', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_naranja_t'                  => ['name' => 'Bmw 6 Naranja', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_gris_t'                     => ['name' => 'Bmw 6 Gris', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
        'pop_bmwm6_negro_t'                    => ['name' => 'Bmw 6 Negro', 'price' => 750000, 'side' => 'civ', 'type' => 'Car'],
    ], ];
